apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: afhd40ntpeoe8a
        type: telegram
        settings:
          bottoken: "${TELEGRAM_BOT_TOKEN}"
          chatid: "1097986020"
          message: |
            {{ range .Alerts -}}
            {{ if eq .Status "firing" -}}
            🔴 [FIRING] {{ .Labels.alertname }}
            {{ .Annotations.summary }}
            {{ .Annotations.description }}
            {{- else -}}
            ✅ [RESOLVED] {{ .Labels.alertname }}
            {{ .Annotations.summary }}
            {{ if .Labels.name }}Контейнер: {{ .Labels.name }}
            {{ end -}}
            Инцидент устранён
            {{- end }}
            {{ end }}
        disableResolveMessage: false
