apiVersion: 1

contactPoints:
  - orgId: 1
    name: Watchdog
    receivers:
      - uid: watchdog_email
        type: email
        settings:
          addresses: "${ALERT_EMAIL}"
          singleEmail: true
        disableResolveMessage: true

  - orgId: 1
    name: Critical
    receivers:
      - uid: critical_email
        type: email
        settings:
          addresses: "${ALERT_EMAIL}"
          singleEmail: true
        disableResolveMessage: false

  - orgId: 1
    name: Warning
    receivers:
      - uid: warning_email
        type: email
        settings:
          addresses: "${ALERT_EMAIL}"
          singleEmail: true
        disableResolveMessage: false
