stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Compile complete."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Application successfully deployed."
