"""add_timestamps_and_trigram_indexes

Revision ID: 896c5d07d433
Revises: a1b2c3d4e5f6
Create Date: 2026-03-26 11:43:10.523994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "896c5d07d433"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "bookings",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.drop_index(op.f("ix_hotel_images_hotel_id"), table_name="hotel_images")
    op.add_column(
        "hotels",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "hotels",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "rooms",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "rooms",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.drop_column("rooms_facilities", "id")
    op.add_column(
        "users",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    # Trigram indexes for hotel search (requires pg_trgm extension)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_hotels_title_trgm ON hotels USING gin (title gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_hotels_location_trgm "
        "ON hotels USING gin (location gin_trgm_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_hotels_location_trgm")
    op.execute("DROP INDEX IF EXISTS idx_hotels_title_trgm")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.add_column(
        "rooms_facilities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_column("rooms", "updated_at")
    op.drop_column("rooms", "created_at")
    op.drop_column("hotels", "updated_at")
    op.drop_column("hotels", "created_at")
    op.create_index(op.f("ix_hotel_images_hotel_id"), "hotel_images", ["hotel_id"], unique=False)
    op.drop_column("bookings", "updated_at")
    op.drop_column("bookings", "created_at")
    # ### end Alembic commands ###
